[patch.crates-io.sub]
path = "/home/ikebe/ros2/rust/ros2_rust_template_ws/install/sub/share/sub/rust"

[patch.crates-io.pub]
path = "/home/ikebe/ros2/rust/ros2_rust_template_ws/install/pub/share/pub/rust"

[patch.crates-io.parameter_multi_thread_sub]
path = "/home/ikebe/ros2/rust/ros2_rust_template_ws/install/parameter_multi_thread_sub/share/parameter_multi_thread_sub/rust"

[patch.crates-io.parameter_multi_thread_pub]
path = "/home/ikebe/ros2/rust/ros2_rust_template_ws/install/parameter_multi_thread_pub/share/parameter_multi_thread_pub/rust"

[patch.crates-io.multi_thread_sub]
path = "/home/ikebe/ros2/rust/ros2_rust_template_ws/install/multi_thread_sub/share/multi_thread_sub/rust"

[patch.crates-io.multi_thread_pub]
path = "/home/ikebe/ros2/rust/ros2_rust_template_ws/install/multi_thread_pub/share/multi_thread_pub/rust"

[patch.crates-io.launcher]
path = "/home/ikebe/ros2/rust/ros2_rust_template_ws/install/launcher/share/launcher/rust"
